project:
  type: website
  output-dir: docs

website:
  title: "Jackson Barnett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.pdf
        text: Resume
      - href: CV.pdf
        text: CV

format:
  html:
    theme: Sandstone
    linkcolor: "#254276"
    css: styles.css
    toc: true

editor: visual

