project:
  type: website
  output-dir: docs

website:
  title: "Jackson Barnett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: barnettportfolio.qmd
        text: Portfolio
      - href: resume.pdf
        text: Resume
      - href: BarnettCV.pdf
        text: CV

format:
  html:
    theme: Sandstone
    backgroundcolor: "#fffef9"
    linkcolor: "#254276"
    css: styles.css
    toc: true

editor: visual

